### ISSUE TITLE
AttributeError: 'module' object has no attribute 'aa'

### ISSUE THREAD

**Issue by piekey1994** [qyyin/AttentionZP#2]
Traceback (most recent call last):
  File ".\data_builder.py", line 614, in <module>
    generate_vector_data()
  File ".\data_builder.py", line 148, in generate_vector_data
    train_zp_info, train_vectorized_sentences = generate_vector(DATA+"train/"+file_name,"./data/train_list")
  File ".\data_builder.py", line 66, in generate_vector
    embedding,words,wd = cPickle.load(read_f)
AttributeError: 'module' object has no attribute 'aa'

emb文件里面有个aa的东西没办法反序列化，请问是不是缺少了什么类文件

**Comment by lpq29743** [comment]
请问这个问题你解决了吗？改了一下代码，就出现这个问题了，很奇怪

**Comment by piekey1994** [comment]
from util import aa就可以了
